# Generated by Django 4.1.6 on 2023-02-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='school_year_id',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='semester',
        ),
    ]
